-- Estrutura PostgreSQL. Não remove registros existentes.
CREATE TABLE IF NOT EXISTS tarefas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(2000),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    observacoes VARCHAR(2000),
    data_criacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_tarefas_nome CHECK (length(btrim(nome)) > 0),
    CONSTRAINT ck_tarefas_status CHECK (status IN ('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDA')),
    CONSTRAINT ck_tarefas_datas CHECK (data_atualizacao >= data_criacao)
);

CREATE INDEX IF NOT EXISTS idx_tarefas_status_id ON tarefas (status, id DESC);
